name: Publish release

on:
  push:
    tags:
      - v**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode gradle properties File
        env:
          ENCODED_STRING: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          echo $ENCODED_STRING | base64 -di > gradle.properties

      - name: Build & deploy release
        run: ./gradlew publishPlugins

      - name: Clean secrets
        if: ${{ always() }}
        run: |
          rm gradle.properties
